<?php
/*---:[ Copyright DIYthemes, LLC. Patent pending. All rights reserved. DIYthemes, Thesis, and the Thesis Theme are registered trademarks of DIYthemes, LLC. ]:---*/
// WARNING: Unless you just LOVE problems, DO NOT EDIT THIS FILE!
require_once(TEMPLATEPATH . '/thesis.php');